sudo: false
language: objective-c
osx_image: xcode12
script: "travis_retry xcodebuild test -workspace .swiftpm/xcode/package.xcworkspace -scheme HTMLAttributor -destination 'platform=iOS Simulator,name=iPhone 11'"
branches:
  only:
    - master
  except:
    - /^v[0-9]/
